# This file allows you to configure Airflow Connections, Pools, and Variables in a single place for local development only.
# NOTE: If putting a dict in conn_extra, please wrap in single quotes.

# For more information, refer to our docs: https://www.astronomer.io/docs/cloud/stable/develop/customize-image#configure-airflowsettingsyaml
# For issues or questions, reach out to support@astronomer.io

airflow:
  connections:
    - conn_id: airflow_db
      conn_type: postgres
      conn_host: postgres
      conn_schema: postgres
      conn_login: postgres
      conn_password: postgres
      conn_port: 5432
      conn_extra:
    - conn_id: my_database_conn_1
      conn_type: postgres
      conn_host:
      conn_schema:
      conn_login:
      conn_password:
      conn_port:
      conn_extra:
  pools:
    - pool_name:
      pool_slot:
      pool_description:
  variables:
    - variable_name: dag_number
      variable_value: 3
    - variable_name: dag_config
      variable_value: "{}"